# Generated by Django 5.0.2 on 2024-02-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
